INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'appUser_001', '{"name": "John", "age": 28}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'user_xyz_02', '{"name": "Alice", "hobbies": ["reading", "gaming"]}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'randomUser123', '{"name": "Bob", "age": 32, "city": "New York"}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'devUser004', '{"name": "Eve", "age": 24, "hobbies": ["coding", "music"]}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'guest005', '{"name": "Charlie", "active": true}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'member006', '{"name": "Diana", "age": 30, "active": false}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'user007Alpha', '{"name": "Frank", "city": "London"}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'uniqueUser008', '{"name": "Grace", "hobbies": ["photography", "travel"]}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'betaTester009', '{"name": "Henry", "active": true, "city": "Paris"}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'user010Gamma', '{"name": "Ivy", "age": 26}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'profile011', '{"name": "Jack", "hobbies": ["cooking", "sports"]}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'appUser012Kappa', '{"name": "Karen", "age": 35, "city": "Berlin"}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'user013Lambda', '{"name": "Leo", "active": false}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'participant014', '{"name": "Mia", "hobbies": ["yoga", "reading", "gaming"], "active": true}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'userOmega015', '{"name": "Nate", "age": 29, "city": "Tokyo"}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'user016Delta', '{"name": "Olivia", "hobbies": ["dance", "music"]}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'player017', '{"name": "Paul", "age": 31, "city": "San Francisco"}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'userPhi018', '{"name": "Quinn", "active": false}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'gamer019', '{"name": "Rachel", "hobbies": ["gaming", "travel", "cooking"], "age": 27}');
INSERT INTO User (id, applicationUserId, jsonCol) VALUES (UUID(), 'sigmaUser020', '{"name": "Steve", "city": "Miami", "active": true}');
