INSERT INTO Action (id, actionName, actionDescription) VALUES 
(UUID(), 'CreateNewProject', 'Create new projects'),
(UUID(), 'Read/ProjectAlpha', 'Read project Alpha'),
(UUID(), 'Write/ProjectAlpha', 'Write project Alpha'),
(UUID(), 'Delete/ProjectAlpha', 'Delete project Alpha'),
(UUID(), 'MergeToDev/ProjectAlpha', 'Merge project Alpha to Dev'),
(UUID(), 'AcceptPRToDev/ProjectAlpha', 'Accept a PR in project Alpha to Dev'),
(UUID(), 'MergeToProd/ProjectAlpha', 'Merge project Alpha to Production'),
(UUID(), 'AddDevs/ProjectAlpha', 'Add devs to project Alpha'),
(UUID(), 'RemoveDevs/ProjectAlpha', 'Remove devs from project Alpha'),
(UUID(), 'AccessProdCluster/ProjectAlpha', 'Access production cluster for project Alpha'),
(UUID(), 'AccessTestResults/ProjectAlpha', 'Access automated test results for project Alpha'),
(UUID(), 'UpdateProdCluster/ProjectAlpha', 'Update production compute cluster for project Alpha'),
(UUID(), 'RunAutomatedTest/ProjectAlpha', 'Trigger automated test run for project Alpha'),
(UUID(), 'UploadAutomatedTestScript/ProjectAlpha', 'Upload a new test script for automated tests for project Alpha'),
(UUID(), 'EditCICDPipeline/ProjectAlpha', 'Edit CICD pipeline for project Alpha'),
(UUID(), 'ProdDBConsoleAccess/ProjectAlpha', 'Access the production database console for Project Alpha'),
(UUID(), 'DevDBConsoleAccess/ProjectAlpha', 'Access the development database console for Project Alpha'),
(UUID(), 'AccessCoreDBSettings/ProjectAlpha', 'Access core database settings for Project Alpha'),
(UUID(), 'AccessAdvancedDBSettings/ProjectAlpha', 'Access advanced database settings for Project Alpha'),
(UUID(), 'EditWhitelist/ProjectAlpha', 'Edit the whitelist for Project Alpha'),
(UUID(), 'EditBlacklist/ProjectAlpha', 'Edit the blacklist for Project Alpha'),
(UUID(), 'RedeployApp/ProjectAlpha', 'Redeploy the application for Project Alpha'),
(UUID(), 'RestartCluster/ProjectAlpha', 'Restart the server cluster for Project Alpha'),
(UUID(), 'EditMessageQueue/ProjectAlpha', 'Edit the message queue settings for Project Alpha'),
(UUID(), 'ViewMessageQueue/ProjectAlpha', 'View the message queue for Project Alpha'),
(UUID(), 'Read/ProjectBeta', 'Read project Beta'),
(UUID(), 'Write/ProjectBeta', 'Write project Beta'),
(UUID(), 'Delete/ProjectBeta', 'Delete project Beta'),
(UUID(), 'MergeToDev/ProjectBeta', 'Merge project Beta to Dev'),
(UUID(), 'AcceptPRToDev/ProjectBeta', 'Accept a PR in project Beta'),
(UUID(), 'MergeToProd/ProjectBeta', 'Merge project Beta to Production'),
(UUID(), 'AddDevs/ProjectBeta', 'Add devs to project Beta'),
(UUID(), 'RemoveDevs/ProjectBeta', 'Remove devs from project Beta'),
(UUID(), 'AccessProdCluster/ProjectBeta', 'Access production cluster for project Beta'),
(UUID(), 'AccessTestResults/ProjectBeta', 'Access automated test results for project Beta'),
(UUID(), 'UpdateProdCluster/ProjectBeta', 'Update production compute cluster for project Beta'),
(UUID(), 'RunAutomatedTest/ProjectBeta', 'Trigger automated test run for project Beta'),
(UUID(), 'UploadAutomatedTestScript/ProjectBeta', 'Upload a new test script for automated tests for project Beta'),
(UUID(), 'EditCICDPipeline/ProjectBeta', 'Edit CICD pipeline for project Beta'),
(UUID(), 'ProdDBConsoleAccess/ProjectBeta', 'Access the production database console for Project Beta'),
(UUID(), 'DevDBConsoleAccess/ProjectBeta', 'Access the development database console for Project Beta'),
(UUID(), 'AccessCoreDBSettings/ProjectBeta', 'Access core database settings for Project Beta'),
(UUID(), 'AccessAdvancedDBSettings/ProjectBeta', 'Access advanced database settings for Project Beta'),
(UUID(), 'EditWhitelist/ProjectBeta', 'Edit the whitelist for Project Beta'),
(UUID(), 'EditBlacklist/ProjectBeta', 'Edit the blacklist for Project Beta'),
(UUID(), 'RedeployApp/ProjectBeta', 'Redeploy the application for Project Beta'),
(UUID(), 'RestartCluster/ProjectBeta', 'Restart the server cluster for Project Beta'),
(UUID(), 'EditMessageQueue/ProjectBeta', 'Edit the message queue settings for Project Beta'),
(UUID(), 'ViewMessageQueue/ProjectBeta', 'View the message queue for Project Beta'),
(UUID(), 'Read/ProjectDelta', 'Read project Delta'),
(UUID(), 'Write/ProjectDelta', 'Write project Delta'),
(UUID(), 'Delete/ProjectDelta', 'Delete project Delta'),
(UUID(), 'MergeToDev/ProjectDelta', 'Merge project Delta to Dev'),
(UUID(), 'AcceptPRToDev/ProjectDelta', 'Accept a PR in project Delta'),
(UUID(), 'MergeToProd/ProjectDelta', 'Merge project Delta to Production'),
(UUID(), 'AddDevs/ProjectDelta', 'Add devs to project Delta'),
(UUID(), 'RemoveDevs/ProjectDelta', 'Remove devs from project Delta'),
(UUID(), 'AccessProdCluster/ProjectDelta', 'Access production cluster for project Delta'),
(UUID(), 'AccessTestResults/ProjectDelta', 'Access automated test results for project Delta'),
(UUID(), 'UpdateProdCluster/ProjectDelta', 'Update production compute cluster for project Delta'),
(UUID(), 'RunAutomatedTest/ProjectDelta', 'Trigger automated test run for project Delta'),
(UUID(), 'UploadAutomatedTestScript/ProjectDelta', 'Upload a new test script for automated tests for project Delta'),
(UUID(), 'EditCICDPipeline/ProjectDelta', 'Edit CICD pipeline for project Delta'),
(UUID(), 'ProdDBConsoleAccess/ProjectDelta', 'Access the production database console for Project Delta'),
(UUID(), 'DevDBConsoleAccess/ProjectDelta', 'Access the development database console for Project Delta'),
(UUID(), 'AccessCoreDBSettings/ProjectDelta', 'Access core database settings for Project Delta'),
(UUID(), 'AccessAdvancedDBSettings/ProjectDelta', 'Access advanced database settings for Project Delta'),
(UUID(), 'EditWhitelist/ProjectDelta', 'Edit the whitelist for Project Delta'),
(UUID(), 'EditBlacklist/ProjectDelta', 'Edit the blacklist for Project Delta'),
(UUID(), 'RedeployApp/ProjectDelta', 'Redeploy the application for Project Delta'),
(UUID(), 'RestartCluster/ProjectDelta', 'Restart the server cluster for Project Delta'),
(UUID(), 'EditMessageQueue/ProjectDelta', 'Edit the message queue settings for Project Delta'),
(UUID(), 'ViewMessageQueue/ProjectDelta', 'View the message queue for Project Delta'),
(UUID(), 'Read/ProjectGamma', 'Read project Gamma'),
(UUID(), 'Write/ProjectGamma', 'Write project Gamma'),
(UUID(), 'Delete/ProjectGamma', 'Delete project Gamma'),
(UUID(), 'MergeToDev/ProjectGamma', 'Merge project Gamma to Dev'),
(UUID(), 'AcceptPRToDev/ProjectGamma', 'Accept a PR in project Gamma'),
(UUID(), 'MergeToProd/ProjectGamma', 'Merge project Gamma to Production'),
(UUID(), 'AddDevs/ProjectGamma', 'Add devs to project Gamma'),
(UUID(), 'RemoveDevs/ProjectGamma', 'Remove devs from project Gamma'),
(UUID(), 'AccessProdCluster/ProjectGamma', 'Access production cluster for project Gamma'),
(UUID(), 'AccessTestResults/ProjectGamma', 'Access automated test results for project Gamma'),
(UUID(), 'UpdateProdCluster/ProjectGamma', 'Update production compute cluster for project Gamma'),
(UUID(), 'RunAutomatedTest/ProjectGamma', 'Trigger automated test run for project Gamma'),
(UUID(), 'UploadAutomatedTestScript/ProjectGamma', 'Upload a new test script for automated tests for project Gamma'),
(UUID(), 'EditCICDPipeline/ProjectGamma', 'Edit CICD pipeline for project Gamma'),
(UUID(), 'ProdDBConsoleAccess/ProjectGamma', 'Access the production database console for Project Gamma'),
(UUID(), 'DevDBConsoleAccess/ProjectGamma', 'Access the development database console for Project Gamma'),
(UUID(), 'AccessCoreDBSettings/ProjectGamma', 'Access core database settings for Project Gamma'),
(UUID(), 'AccessAdvancedDBSettings/ProjectGamma', 'Access advanced database settings for Project Gamma'),
(UUID(), 'EditWhitelist/ProjectGamma', 'Edit the whitelist for Project Gamma'),
(UUID(), 'EditBlacklist/ProjectGamma', 'Edit the blacklist for Project Gamma'),
(UUID(), 'RedeployApp/ProjectGamma', 'Redeploy the application for Project Gamma'),
(UUID(), 'RestartCluster/ProjectGamma', 'Restart the server cluster for Project Gamma'),
(UUID(), 'EditMessageQueue/ProjectGamma', 'Edit the message queue settings for Project Gamma'),
(UUID(), 'ViewMessageQueue/ProjectGamma', 'View the message queue for Project Gamma'),
(UUID(), 'DeleteAllProjects', 'Delete all projects'),
(UUID(), 'WriteAllProjects', 'Write all projects'),
(UUID(), 'ReadAllProjects', 'Read all projects');