INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'Login', 'User login action');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'Logout', 'User logout action');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'ViewProfile', 'View user profile');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'EditProfile', 'Edit user profile details');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'DeleteAccount', 'Delete user account');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'CreatePost', 'Create a new post');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'EditPost', 'Edit an existing post');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'DeletePost', 'Delete a specific post');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'LikePost', 'Like a post');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'Comment', 'Comment on a post');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'SharePost', 'Share a post');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'FollowUser', 'Follow a user');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'UnfollowUser', 'Unfollow a user');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'SendMessage', 'Send a message');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'ReadMessage', 'Read a received message');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'ArchiveMessage', 'Archive a message');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'ReportIssue', 'Report an issue or bug');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'UpdateSettings', 'Update account settings');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'ActivateNotifications', 'Activate notifications');
INSERT INTO Action (id, actionName, actionDescription) VALUES (UUID(), 'DeactivateNotifications', 'Deactivate notifications');
