INSERT INTO Context (id, contextDescription, operator, entity, textValue, timeValue1, timeValue2) VALUES 
(UUID(), 'Access to server room during business hours', 'BETWEEN', 'ServerRoomAccess', NULL, '09:00:00', '17:00:00'),
(UUID(), 'No access to development servers during maintenance', 'NOT BETWEEN', 'DevServerMaintenance', NULL, '02:00:00', '04:00:00'),
(UUID(), 'Access to project resources from main office', 'IN', 'ProjectLocationAccess', 'MainOffice', NULL, NULL),
(UUID(), 'Project access restricted to specific regions', 'IN', 'ProjectRegionalAccess', 'US,EU,JP', NULL, NULL),
(UUID(), 'Only administrators can access user data', '==', 'UserDataAccess', 'Administrator', NULL, NULL),
(UUID(), 'Interns cannot access financial records', '!=', 'FinancialRecordAccess', 'Intern', NULL, NULL),
(UUID(), 'Read access to confidential project documents', '==', 'ProjectDocType', 'Confidential', NULL, NULL),
(UUID(), 'Edit access to public documentation', '==', 'PublicDocEdit', 'Public', NULL, NULL),
(UUID(), 'Access to highly sensitive database', '==', 'DatabaseSensitivity', 'High', NULL, NULL),
(UUID(), 'Access to less sensitive database', '==', 'DatabaseSensitivity', 'Low', NULL, NULL),
(UUID(), 'Expense approval limit for regular employees', '<=', 'ExpenseLimit', NULL, '1000', NULL),
(UUID(), 'Expense approval limit for managers', '<=', 'ExpenseLimit', NULL, '5000', NULL),
(UUID(), 'System access for active employee accounts', '==', 'EmployeeAccountStatus', 'Active', NULL, NULL),
(UUID(), 'No system access for suspended employee accounts', '==', 'EmployeeAccountStatus', 'Suspended', NULL, NULL),
(UUID(), 'Application access from company-issued devices', 'IN', 'DeviceTypeAccess', 'Laptop,Desktop', NULL, NULL),
(UUID(), 'Restrict application access from personal mobile devices', 'NOT IN', 'DeviceTypeAccess', 'Smartphone,Tablet', NULL, NULL),
(UUID(), 'Feature available in app version 5.0 and above', '>=', 'FeatureAppVersion', NULL, '5.0', NULL),
(UUID(), 'Feature not available in app versions below 5.0', '<', 'FeatureAppVersion', NULL, '5.0', NULL),
(UUID(), 'Project access for users active within the last month', '>', 'UserLastActivity', NULL, '2023-01-01 00:00:00', NULL),
(UUID(), 'No project access for users inactive for over 6 months', '<', 'UserLastActivity', NULL, '2022-07-01 00:00:00', NULL),
(UUID(), 'Tool access for engineering and product teams', 'IN', 'UserGroupToolAccess', 'Engineering,Product', NULL, NULL),
(UUID(), 'No tool access for external consultant groups', 'NOT IN', 'UserGroupToolAccess', 'Consultants', NULL, NULL),
(UUID(), 'Access to resources for Project Alpha', '==', 'ProjectResourceAccess', 'Alpha', NULL, NULL),
(UUID(), 'No access to resources for Project Beta', '!=', 'ProjectResourceAccess', 'Beta', NULL, NULL),
(UUID(), 'Full tool access for permanent employees', '==', 'EmployeeContractType', 'Permanent', NULL, NULL),
(UUID(), 'Restriction for non-enterprise contract users', '!=', 'ContractType', 'Enterprise', NULL, NULL),
(UUID(), 'Access for high-security clearance', '>=', 'SecurityClearance', NULL, 'Level3', NULL),
(UUID(), 'Restriction for low-security clearance', '<', 'SecurityClearance', NULL, 'Level3', NULL),
(UUID(), 'Access for cloud infrastructure management', '==', 'InfrastructureRole', 'CloudAdmin', NULL, NULL),
(UUID(), 'Restriction from critical server access', '!=', 'ServerAccess', 'Critical', NULL, NULL),
(UUID(), 'Access to development environment', 'IN', 'EnvironmentAccess', 'Development,Staging', NULL, NULL),
(UUID(), 'Restriction from production environment', '!=', 'EnvironmentAccess', 'Production', NULL, NULL),
(UUID(), 'Access for team leads', '==', 'UserRole', 'TeamLead', NULL, NULL),
(UUID(), 'Access based on employment duration', '>=', 'EmploymentDuration', NULL, '365', NULL),
(UUID(), 'Access to financial records', '==', 'DataAccess', 'Financial', NULL, NULL),
(UUID(), 'Restriction from HR records', '!=', 'DataAccess', 'HR', NULL, NULL),
(UUID(), 'Access for on-site employees', '==', 'EmployeeType', 'OnSite', NULL, NULL),
(UUID(), 'Restriction for remote employees', '==', 'EmployeeType', 'Remote', NULL, NULL);
