INSERT INTO User (id, applicationUserId, jsonCol) VALUES 
(UUID(), 'JohnDoe', '{"ServerRoomAccess": "09:00:00,17:00:00", "ProjectLocationAccess": ["MainOffice"]}'),
(UUID(), 'JaneSmith', NULL),
(UUID(), 'AliceJohnson', '{"DevServerMaintenance": "02:00:00,04:00:00", "UserDataAccess": "Administrator"}'),
(UUID(), 'BobBrown', '{"ProjectRegionalAccess": ["US","EU","JP"], "ExpenseLimit": "1000"}'),
(UUID(), 'CharlieDavis', NULL),
(UUID(), 'DianaEvans', '{"FinancialRecordAccess": "Intern", "EmployeeAccountStatus": "Active"}'),
(UUID(), 'EthanFoster', '{"ProjectDocType": "Confidential", "DatabaseSensitivity": "High"}'),
(UUID(), 'FionaGreen', '{"PublicDocEdit": "Public", "FeatureAppVersion": "5.0"}'),
(UUID(), 'GeorgeHarris', NULL),
(UUID(), 'HannahIvy', '{"DatabaseSensitivity": "Low", "DeviceTypeAccess": ["Laptop","Desktop"]}'),
(UUID(), 'IanJones', '{"ExpenseLimit": "5000", "EmployeeAccountStatus": "Suspended"}'),
(UUID(), 'JuliaKlein', NULL),
(UUID(), 'KevinLee', '{"FeatureAppVersion": "4.9", "UserLastActivity": "2023-01-01 00:00:00"}'),
(UUID(), 'LauraMorgan', '{"DeviceTypeAccess": ["Smartphone","Tablet"], "UserGroupToolAccess": ["Engineering","Product"]}'),
(UUID(), 'MikeNolan', '{"ProjectResourceAccess": "Alpha", "EmployeeContractType": "Permanent"}'),
(UUID(), 'NinaOwens', '{"ServerAccess": "Critical", "EnvironmentAccess": "Development,Staging"}'),
(UUID(), 'OliverPerez', NULL),
(UUID(), 'PamelaQuinn', '{"UserLastActivity": "2022-06-30 00:00:00", "SecurityClearance": "Level3"}'),
(UUID(), 'QuincyReed', '{"InfrastructureRole": "CloudAdmin", "ContractType": "Enterprise"}'),
(UUID(), 'RachelStone', NULL);
